trincrypt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'trincrypt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('trincrypt_users.urls', namespace="trincrypt_users")),
    url(r'^group/', include('trincrypt_groups.urls', namespace="trincrypt_groups")),
    url(r'^post/', include('trincrypt_posts.urls', namespace="trincrypt_posts")),
    url(r'^', include('twitter_auth.urls')),
)

trincrypt_groups/urls.py
from django.conf.urls import patterns, url
from trincrypt_groups import views

urlpatterns = patterns( '',
		url(r'^$', views.group, name='group'),
		url(r'^(?P<group_id>\d+)$', views.details, name='details'),
	)

trincrypt_groups/models.py
from django.db import models
from trincrypt_users.models import User

class Group(models.Model):
	name = models.CharField(max_length=30)
	members = models.ManyToManyField(User, verbose_name='group members', related_name='group_members')
	admin = models.ForeignKey(User, verbose_name='admin user', related_name='admin_user')		# User who can admin the group
	secret_key = models.CharField(max_length=200)

	def __str__(self):
		return self.name

trincrypt_groups/views.py
from django.shortcuts import render, get_object_or_404
from trincrypt_users.models import User
from trincrypt_groups.models import Group
from trincrypt_posts.models import Post

def group(request):
	user = get_object_or_404(User, pk=request.session['trincrypt_user_id'])
	groups = Group.objects.all()
	context = {'user':user, 'groups':groups}
	return render(request, 'trincrypt_groups/group.html', context)

def details(request, group_id):
	user = get_object_or_404(User, pk=request.session['trincrypt_user_id'])
	group = get_object_or_404(Group, pk=group_id)
	posts = Post.objects.get(group=group_id)
	context = {'user':user, 'group':group, 'posts':posts}
	return render(request, 'trincrypt_groups/details.html', context)

trincrypt_groups/templates/trincrypt_groups/base.html
<html> 
	<head>
		<title>{% block title %}Trincrypt{% endblock %}</title>
		<link rel="stylesheet" href="/media/style.css">
</head>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

trincrypt_groups/templates/trincrypt_groups/details.html
{% extends "trincrypt_groups/base.html" %}

	{% block content %}
	<h3> {{ group.name }} </h3>
	<p>secret key: {{group.secret_key}}</p>
	{% for post in posts %}

	{% endfor %}
	{% endblock %}	}

trincrypt_groups/templates/trincrypt_groups/group.html
{% extends "trincrypt_posts/base.html" %}

	{% block content %}
	<h3> Groups </h3>
	{% for group in groups %}
		<li><a href="{% url 'trincrypt_groups:details' group.id %}">{{ group.name }}</a></li>
	{% endfor %}
	{% endblock %}	}