trincrypt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'trincrypt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('trincrypt_users.urls', namespace="trincrypt_users")),
    url(r'^group/', include('trincrypt_groups.urls', namespace="trincrypt_groups")),
    url(r'^post/', include('trincrypt_posts.urls', namespace="trincrypt_posts")),
    url(r'^', include('twitter_auth.urls')),
)

trincrypt_posts/urls.py
from django.conf.urls import patterns, url
from trincrypt_posts import views

urlpatterns = patterns( '',
		url(r'^create/$', views.create, name='create'),
		url(r'^details/$', views.details, name='details'),
		url(r'^(?P<post_id>\d+)/$', views.display, name='display'),
	)

trincrypt_posts/models.py
from django.db import models
from trincrypt_groups.models import Group
from trincrypt_users.models import User

class Post(models.Model):
	# twitter id of post
	user = models.ForeignKey(User)
	group = models.ForeignKey(Group)
	status_id = models.CharField(max_length=30)
	message = models.CharField(max_length=200)			# encrypted message
	pub_date = models.DateTimeField('date published')

trincrypt_posts/views.py
from django.shortcuts import render, get_object_or_404
from trincrypt_users.models import User
from trincrypt_groups.models import Group
from django.utils import timezone
from django import forms
from twitter_auth.utils import *
from models import Post
import crypto

def create(request):
	user = get_object_or_404(User, pk=request.session['trincrypt_user_id'])
	groups = Group.objects.filter(members=user)
	return render(request, 'trincrypt_posts/create.html', {'groups':groups})

def details(request):
	user = get_object_or_404(User, pk=request.session['trincrypt_user_id'])
	groups = Group.objects.filter(members=user)
	if request.method == 'POST':
		message = request.POST['message']
		try:
			group = Group.objects.get(id=request.POST['group'])
		except (KeyError, Group.DoesNotExist):
			return render(request, 'trincrypt_posts/create.html', {'groups':groups})
		# encrypt message
		secret_message = crypto.encrypt(message, crypto.convert_hex_to_secret(group.secret_key))
		# post tweet
		status = create_status(request, secret_message)
		#save post
		post = Post(user=user, status_id=status.id_str, group=group, message=secret_message, pub_date=timezone.now())
		post.save()
		context = {'post':post, 'group':group, 'message':message}
		return render(request, 'trincrypt_posts/details.html', context)
	else:
		return render(request, 'trincrypt_posts/create.html', {'groups':groups})

def display(request, post_id):
	user = get_object_or_404(User, pk=request.session['trincrypt_user_id'])
	post = get_object_or_404(Post, status_id=post_id)
	group = get_object_or_404(Group, id=post.group)
	secret_message = post.message
	message = decrypt(secret_message, convert_hex_to_secret(group.secret_key))
	context = {'user':user, 'post':post, 'group':group, 'message':message}
	return render(request, 'trincrypt_posts/display.html', context)

class CreatePostForm(forms.Form):
	message = forms.CharField(label='Message', max_length=95, widget=forms.Textarea)
	groups = forms.ChoiceField(label='Group')

trincrypt_posts/templates/trincrypt_posts/base.html
<html> 
	<head>
		<title>{% block title %}Trincrypt{% endblock %}</title>
		<link rel="stylesheet" href="/media/style.css">
</head>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

trincrypt_posts/templates/trincrypt_posts/create.html
{% extends "trincrypt_posts/base.html" %}

	{% block content %}
	<h3> Create a tweet that will be encrypted and posted to twitter </h3>
	<form action="{% url 'trincrypt_posts:details' %}" method="post">
	{% csrf_token %}
	<label for="message">Message: </label>
	<input id="message" type="text" name="message" maxlength="95"><br />
	{% for group in groups %}
		<input type="radio" name="group" id="group{{ forloop.counter }}" value="{{ group.id }}" />
    	<label for="group{{ forloop.counter }}">{{ group.name }}</label><br />
	{% endfor %}
	<input type="submit" value="Submit" />
	</form>
	{% endblock %}

trincrypt_posts/templates/trincrypt_posts/details.html
{% extends "trincrypt_posts/base.html" %}

	{% block content %}
	<h3> Message received </h3>
	<p>plaintext: {{message}}</p>
	<p>ciphertext: {{post.message}}</p>
	<p>Group: {{ group.name }}</p>
	<p>Status: {{ post.status_id }}</p>
	{% endblock %}

trincrypt_posts/templates/trincrypt_posts/display.html
{% extends "trincrypt_posts/base.html" %}

	{% block content %}
	<h3> Tweet Details </h3>
	<p>plaintext: {{message}}</p>
	<p>ciphertext: {{post.message}}</p>
	<p>Group: {{ group.name }}</p>
	<p>Status: {{ post.status_id }}</p>
	{% endblock %}