trincrypt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'trincrypt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('trincrypt_users.urls', namespace="trincrypt_users")),
    url(r'^group/', include('trincrypt_groups.urls', namespace="trincrypt_groups")),
    url(r'^post/', include('trincrypt_posts.urls', namespace="trincrypt_posts")),
    url(r'^', include('twitter_auth.urls')),
)

trincrypt_groups/urls.py
from django.conf.urls import patterns, url
from trincrypt_groups import views

urlpatterns = patterns( '',
		url(r'^$', views.group, name='group'),
		url(r'^(?P<group_id>\d+)$', views.details, name='details'),
	)

trincrypt_posts/urls.py
from django.conf.urls import patterns, url
from trincrypt_posts import views

urlpatterns = patterns( '',
		url(r'^create/$', views.create, name='create'),
		url(r'^details/$', views.details, name='details'),
		url(r'^(?P<post_id>\d+)/$', views.display, name='display'),
	)

trincrypt_users/urls.py
from django.conf.urls import patterns, url
from trincrypt_users import views

urlpatterns = patterns( '',
		# user profile /user/<user-id>
		url(r'^(?P<trincrypt_user_id>\d+)$', views.profile, name='profile'),
		url(r'^register/$', views.register, name='register'),
	)

trincrypt_users/models.py
from django.utils import timezone
from django.db import models

class User(models.Model):
	id_tw = models.CharField(max_length=20, primary_key=True)
	name = models.CharField(max_length=20)
	screen_name = models.CharField(max_length=20)
	date_joined = models.DateTimeField(default=timezone.now())

	def __str__(self):
		return self.id_tw

trincrypt_users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseNotFound
from models import User
from utils import *
from twitter_auth.utils import *

def profile(request, trincrypt_user_id):
	user = get_object_or_404(User, pk=trincrypt_user_id)
	twitter_user = get_twitter_user_from_request(request)
	return render(request, 'trincrypt_users/profile.html', {'user':user, 'twitter_user':twitter_user})

def register(request):
	twitter_user = get_twitter_user_from_request(request)
	is_registered = is_trincrypt_user(twitter_user.id_str)
	user = None
	if is_registered is False:
		user = User(twitter_user.id_str, twitter_user.name, twitter_user.screen_name)
		user.save()
	else:
		user = User.objects.get(pk=twitter_user.id_str)
	return render(request, 'trincrypt_users/register.html', {'is_registered':is_registered, 'user':user, 'twitter_user':twitter_user})

trincrypt_users/templates/trincrypt_users/base.html
<html> 
	<head>
		<title>{% block title %}Trincrypt{% endblock %}</title>
		<link rel="stylesheet" href="/media/style.css">
</head>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

trincrypt_users/templates/trincrypt_users/profile.html
{% extends "trincrypt_users/base.html" %}
	{%block title%}User Profile{% endblock%}
	{% block content %}
	<div id="container">
			<img src="{{twitter_user.profile_image_url}}" />
			<h3>{{user.name}}</h3>
			<p>{{user.screen_name}}<p/>
			<p>Date Joined: {{user.date_joined}}<p/>
			<a href="{% url 'trincrypt_posts:create' %}" title="create">Create tweet</a>
			<br />
			<a href="{% url 'trincrypt_groups:group' %}" title="group">View Groups</a>
			<br />
			<a href="/logout/" title="logout">logout</a>
	</div>
	{% endblock %}

trincrypt_users/templates/trincrypt_users/register.html
{% extends "trincrypt_users/base.html" %}

	{% block content %}
		{% if is_registered %}  
			<h1>Sorry, you are already registered!</h1>
		{% else %}
			<h1>You are now registered!</h1>
			<p> Welcome to the site {{ twitter_user.name }}! </p>
		{% endif %}
		<a href="{% url 'trincrypt_users:profile' twitter_user.id_str %}" title="profile">go to profile</a>
	{% endblock %}