trincrypt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'trincrypt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('trincrypt_users.urls', namespace="trincrypt_users")),
    url(r'^group/', include('trincrypt_groups.urls', namespace="trincrypt_groups")),
    url(r'^post/', include('trincrypt_posts.urls', namespace="trincrypt_posts")),
    url(r'^', include('twitter_auth.urls')),
)

trincrypt_users/urls.py
from django.conf.urls import patterns, url
from trincrypt_users import views

urlpatterns = patterns( '',
		# user profile /user/<user-id>
		url(r'^(?P<trincrypt_user_id>\d+)$', views.profile, name='profile'),
		url(r'^register/$', views.register, name='register'),
	)

twitter_auth/urls.py
from django.conf.urls import patterns, url
from twitter_auth.views import *

urlpatterns = patterns('twitter_auth.views',
    url(r'^$', view=main, name='main'),
    url(r'^callback/$', view=callback, name='auth_return'),
    url(r'^logout/$', view=unauth, name='oauth_unauth'),
    url(r'^auth/$', view=auth, name='oauth_auth'),
    url(r'^info/$', view=info, name='info'),
)

twitter_auth/models.py
from django.db import models

# Create your models here.

twitter_auth/views.py
# Create your views here.
import tweepy
from django.http import *
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from utils import *
from trincrypt_users.utils import *

def main(request):
	"""
	main view of app, either login page or info page
	"""
	# if we haven't authorised yet, direct to login page
	if check_key(request):
		return HttpResponseRedirect(reverse('info'))
	else:
		return render_to_response('twitter_auth/login.html')
 
def unauth(request):
	"""
	logout and remove all session data
	"""
	if check_key(request):
		request.session.clear()
		logout(request)
	return HttpResponseRedirect(reverse('main'))

def info(request):
	"""
	display some user info to show we have authenticated successfully
	"""
	if check_key(request):
		user = get_twitter_user_from_request(request)
		is_registered = is_trincrypt_user(user.id_str)
		return render_to_response('twitter_auth/info.html', {'user' : user, 'is_registered':is_registered})
	else:
		return HttpResponseRedirect(reverse('main'))

def auth(request):
    # start the OAuth process, set up a handler with our details
    oauth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET, CALLBACK)
    # direct the user to the authentication url
    # if user is logged-in and authorized then transparently goto the callback URL
    try:
    	auth_url = oauth.get_authorization_url()
    except tweepy.TweepError:
    	print 'Error getting request token'
    	return HttpResponse('error', status=500)
    # store the request token
    #request.session['unauthed_token_tw'] = (oauth.request_token['oauth_token'], oauth.request_token['oauth_token_secret']) 
    request.session['unauthed_token_tw'] = oauth.request_token
    return HttpResponseRedirect(auth_url)

def callback(request):
    verifier = request.GET.get('oauth_verifier')
    oauth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    token = request.session.get('unauthed_token_tw')
    # remove the request token now we don't need it
    request.session.delete('unauthed_token_tw')
    oauth.request_token = token
    # get the access token and store
    try:
    	oauth.get_access_token(verifier)
    except tweepy.TweepError:
    	print 'Error, failed to get access token'
    request.session['access_key_tw'] = oauth.access_token
    request.session['access_secret_tw'] = oauth.access_token_secret
    request = set_trincrypt_user_id(request)
    response = HttpResponseRedirect(reverse('info',))
    return response

def check_key(request):
	"""
	Check to see if we already have an access_key stored, if we do then we have already gone through 
	OAuth. If not then we haven't and we probably need to.
	"""
	try:
		access_key = request.session.get('access_key_tw', None)
		if not access_key:
			return False
	except KeyError:
		return False
	return True

twitter_auth/templates/twitter_auth/base.html
<html> 
	<head>
		<title>{% block title %}TwitterAuthDjango{% endblock %}</title>
		<link rel="stylesheet" href="/media/style.css">
</head>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

twitter_auth/templates/twitter_auth/info.html
{% extends "twitter_auth/base.html" %}

	{% block content %}
		<div id="container">
			<img src="{{user.profile_image_url}}" />
			<h3>{{user.name}}</h3>
			<p>{{user.screen_name}}<p/>
			<br />
			{% if is_registered %}
			<a href="{% url 'trincrypt_users:profile' user.id_str%}">Check out trincrypt profile!</a>
			{% else %}
			<a href="{% url 'trincrypt_users:register' %}">Register now</a>
			{% endif %}
			<br />
			<a href="/logout/" title="logout">logout</a>
		</div>
	{% endblock %}

twitter_auth/templates/twitter_auth/login.html
{% extends "twitter_auth/base.html" %}
		
	{% block content %}
	<div id="container">
		<h2>Welcome!</h2>
		<p>Sign in with Twitter to begin.</p>
		<p><a href="/auth/"><img src="http://g.twimg.com/dev/sites/default/files/images_documentation/sign-in-with-twitter-gray.png" alt="sign in with twitter" /></a></p>
	</div>
	{% endblock %}